remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: 东南大学飞跃手册
logo: /assets/img/SEU_.png
description: This page is for every SEUer.
google_analytics:
theme: jekyll-theme-minimal
gem "github-pages", group: :jekyll_plugins
